### PR TITLE
Added proximity logic back

### LINKED ISSUE #45: Add Correct proximity logic back to master branch
Logic for private api. This is the only option on some older phones that have funky Power management settings, especially samsung:

https://github.com/lukeweber/webrtc-jingle-client/blob/stable/voice-client-example/src/main/java/com/tuenti/voice/example/util/WakeLockManager.java

Logic using a proximity sensor, if you can't use the private api:
https://github.com/lukeweber/webrtc-jingle-client/blob/stable/voice-client-example/src/main/java/com/tuenti/voice/example/util/ProximitySensor.java

All of it is driven from here:
https://github.com/lukeweber/webrtc-jingle-client/blob/stable/voice-client-example/src/main/java/com/tuenti/voice/example/ui/activity/CallInProgressActivity.java

OnPause() logic is particularly important for making sure to stop proximitysensor correctly based on whether the screen is on or off when this method is hit.

### PR DESCRIPTION
**Pull request by jreyes**
This fixes https://github.com/lukeweber/webrtc-jingle-client/issues/45

### CODE REVIEW

**Comment by lukeweber** [comment]
What about the logic for headset plugged, bluetooth and when the phone is horizontal?

**Comment by jreyes** [comment]
headset/bluetooth/speaker since is a core util i think it should be in another class, working currently on that one. The phone horizontal is so it wont turn off when the phone is like that?

**Comment by lukeweber** [comment]
Horizontal is actually equivalent to phone laying flat. Naming is just
funky.

**Comment by lukeweber** [comment]
Cool, merged this.

**Pull request closed without merging**
