### PR TITLE
libjingle unittest support

### PR DESCRIPTION
**Pull request by dmonakhov**
Hi please pull unittest changes.
TODO: 1) Test execution automation should be improved.
             2)  For now it is compiled only armabi-v7a.
In my case only sslDtls related  test failed, all other succeed.

### CODE REVIEW

**Comment by lukeweber** [comment]
Thanks a lot for the help on this one. This looks like a good first step to allowing us to test. I think I'll give a shot at adding armv5 support tomorrow, just for completeness if it's not too much of a pain. At the moment it seems to stutter on the atomicops_unittest.cc, and I think this is armv5 because it's a block that's triggered on **arm**. I know chromium guys only support armv7 as armv5 isn't even supported anymore in AOSP.

StaticLibrary  : libwebrtc_voice.a
Compile++ thumb  : jingle_unittest <= atomicops_unittest.cc
Compile++ thumb  : jingle_unittest <= buffer_unittest.cc
/var/folders/gk/t4tg6fp94272jmnjq67q67xc0000gp/T//ccCQ8zgD.s: Assembler messages:
/var/folders/gk/t4tg6fp94272jmnjq67q67xc0000gp/T//ccCQ8zgD.s:9054: Error: selected processor does not support Thumb mode `dmb'
/var/folders/gk/t4tg6fp94272jmnjq67q67xc0000gp/T//ccCQ8zgD.s:9093: Error: selected processor does not support Thumb mode`ldrex r4,[r3]'
/var/folders/gk/t4tg6fp94272jmnjq67q67xc0000gp/T//ccCQ8zgD.s:9095: Error: selected processor does not support Thumb mode `strex r5,r4,[r3]'
/var/folders/gk/t4tg6fp94272jmnjq67q67xc0000gp/T//ccCQ8zgD.s:9096: Error: selected processor does not support Thumb mode`teq r5,#0'

**Comment by lukeweber** [comment]
I made some small changes to libjingle to support mips, and make x86 work, and make armv5 compile pass. Moved your gen_test script into tools and updated to the new version of the generate_native_test.py script, and changed to use x86. As well I bumped the base revision of chromium to be much more up to date. This meant I had to rebuilt my build-override directory so it was in sync.

Changes in webrtc:
https://github.com/lukeweber/webrtc-jingle-client/commit/bc0aa271f0a1be44d3845f1a01e155d9ddcb3c2e

Changes in libjingle:
https://github.com/lukeweber/libjingle-override/commit/8c3b7c497aa5b19466bc0acc8d6731298b0a3571

It seems to build now, but ant seems to think I'm crazy and don't have environment variable set like ANDROID_SDK_ROOT set that I'm sure I do. I'm not sure if this is because Chromium tools are hostile to mac, or if it's a bug in something I haven't yet implemented.

Would be curious if you checkout webrtc-jingle-override on the unittest branch works for you. Anyhow I'll debug and figure out what's missing on mac unless you have an idea what's wrong with ant and get to it first.

Thanks a lot for the nice patch

Luke

**Comment by lukeweber** [comment]
Error for reference:

BUILD FAILED
/Users/luke/projects/webrtc-jingle-client/trunk/voice_test/x86/libjingle_p2p_unittest/native_test_apk.xml:21: The following error occurred while executing this line:
/Users/luke/projects/webrtc-jingle-client/trunk/build/android/ant/common.xml:74: The following error occurred while executing this line:
/Users/luke/projects/webrtc-jingle-client/trunk/build/android/ant/common.xml:51: The following error occurred while executing this line:
/Users/luke/projects/webrtc-jingle-client/trunk/build/android/ant/common.xml:32: Value checked failed for property: sdk.dir : /Users/luke/projects/webrtc-jingle-client/trunk/voice_test/x86/libjingle_p2p_unittest/${ANDROID_SDK_ROOT}.           Property value contains an uninitialized environment variable.

**Comment by dmonakhov** [comment]
Ok i've uploaded update for unittest branch here https://github.com/dmonakhov/webrtc-jingle-client/commit/9bfd836a7f81da3ad7e299e2d9891ce3a265eef7

**Comment by dmonakhov** [comment]
Ohh, can you please also pull two small fixes from here https://github.com/dmonakhov/webrtc-jingle-client/commit/13a8c1a530642720569b28842557774dffd51ada

**Pull request closed without merging**
